# Generated by Django 3.2.5 on 2021-08-08 09:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('MAINAPP', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posted_on', models.DateField(blank=True, default=django.utils.timezone.now)),
                ('posted_by', models.CharField(blank=True, max_length=100)),
                ('article_name', models.CharField(max_length=200)),
                ('article_caption', models.TextField(blank=True)),
                ('article_introduction', models.TextField(blank=True)),
                ('article_sub_heading1', models.CharField(blank=True, max_length=200)),
                ('article_sub_body1', models.TextField(blank=True)),
                ('article_conclusion', models.TextField(blank=True)),
                ('article_image', models.ImageField(blank=True, help_text='crop image as square before upload to get uniform size in the page', null=True, upload_to='')),
                ('add_article_to_home', models.BooleanField(blank=True, default=False, help_text='Yes will enable to display it on home page', null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
