# Generated by Django 3.2.5 on 2021-08-16 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MAINAPP', '0002_auto_20210808_1456'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewer_name', models.CharField(blank=True, max_length=200)),
                ('reviewer_email', models.EmailField(blank=True, max_length=200)),
                ('reviewer_message', models.TextField(blank=True, max_length=5000)),
            ],
        ),
    ]
