# Generated by Django 3.2.5 on 2021-08-17 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MAINAPP', '0004_diagnosistool'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscribe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscriber_name', models.CharField(blank=True, max_length=300)),
                ('subscriber_email', models.EmailField(blank=True, max_length=300)),
            ],
        ),
    ]
