# Generated by Django 3.2.5 on 2021-08-17 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MAINAPP', '0005_subscribe'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Subscribe',
            new_name='Subscriber',
        ),
    ]
